import icons from "./icons";
import images from "./images";
import { COLORS } from "./theme";

const slides = [
    {
        id: '1',
        image: images.Beauty,
        title: "Beauty parlour at your home",
        subTitle: " Lorem ipsum is a placeholder text commonly used to demonstrate the visual.",
    },
    {
        id: '2',
        image: images.Service,
        title: " Plumber & expart nearby you",
        subTitle: " Lorem ipsum is a placeholder text commonly used to demonstrate the visual.",
    },
    {
        id: '3',
        image: images.Cleaning,
        title: "Professional home cleaning",
        subTitle: " Lorem ipsum is a placeholder text commonly used to demonstrate the visual.",
    }
]

const banners = [
    {
        id: 1,
        imageBG: images.OrangeBG,
        discount: "30%",
        OfferName: "Today's Special!",
        SubTitle: "Get discount for every order, only valid for today",
        Cleaner: images.Cleaner1,
    },
    {
        id: 2,
        imageBG: images.YellowBG,
        discount: "25%",
        OfferName: "Today's Special!",
        SubTitle: "Get discount for every order, only valid for today",
        Cleaner: images.Cleaner2,
    },
    {
        id: 3,
        imageBG: images.GreenBG,
        discount: "30%",
        OfferName: "Today's Special!",
        SubTitle: "Get discount for every order, only valid for today",
        Cleaner: images.Cleaner3,
    },
    {
        id: 4,
        imageBG: images.LavenderBlueBG,
        discount: "30%",
        OfferName: "Today's Special!",
        SubTitle: "Get discount for every order, only valid for today",
        Cleaner: images.Cleaner6,
    },
    {
        id: 5,
        imageBG: images.MintGreenBG,
        discount: "30%",
        OfferName: "Today's Special!",
        SubTitle: "Get discount for every order, only valid for today",
        Cleaner: images.Cleaner9,
    },
    {
        id: 6,
        imageBG: images.MarronBG,
        discount: "30%",
        OfferName: "Today's Special!",
        SubTitle: "Get discount for every order, only valid for today",
        Cleaner: images.Cleaner3,
    },
    {
        id: 7,
        imageBG: images.PeachBG,
        discount: "30%",
        OfferName: "Today's Special!",
        SubTitle: "Get discount for every order, only valid for today",
        Cleaner: images.Cleaner1,
    },
    {
        id: 8,
        imageBG: images.DuskyPinkBG,
        discount: "30%",
        OfferName: "Today's Special!",
        SubTitle: "Get discount for every order, only valid for today",
        Cleaner: images.Cleaner6,
    },
    {
        id: 9,
        imageBG: images.YellowBG,
        discount: "30%",
        OfferName: "Today's Special!",
        SubTitle: "Get discount for every order, only valid for today",
        Cleaner: images.Cleaner9,
    },
    {
        id: 10,
        imageBG: images.BeigeBG,
        discount: "30%",
        OfferName: "Today's Special!",
        SubTitle: "Get discount for every order, only valid for today",
        Cleaner: images.Cleaner2,
    },
    {
        id: 11,
        imageBG: images.LavenderBG,
        discount: "30%",
        OfferName: "Today's Special!",
        SubTitle: "Get discount for every order, only valid for today",
        Cleaner: images.Cleaner3,
    }
]

const service = [
    {
        id: 1,
        icon: icons.Cleaning,
        title: "Cleaning",
        color: COLORS.purple,
        colorBg: COLORS.purpleTrans,
        nav: "Cleaning"
    },
    {
        id: 2,
        icon: icons.Repairing,
        title: "Repairing",
        color: COLORS.orange,
        colorBg: COLORS.orangeTrans,
        nav: "Repairing",
    },
    {
        id: 3,
        icon: icons.Painting,
        title: "Painting",
        color: COLORS.blue,
        colorBg: COLORS.blueTrans,
        nav: "Painting",
    },
    {
        id: 4,
        icon: icons.Laundry,
        title: "Laundry",
        color: COLORS.lightYellow,
        colorBg: COLORS.lightYellowTrans,
        nav: "Laundry",
    },
    {
        id: 5,
        icon: icons.Appliance,
        title: "Appliance",
        color: COLORS.red,
        colorBg: COLORS.redTrans,
        nav: "Appliance",
    },
    {
        id: 6,
        icon: icons.Plumbing,
        title: "Plumbing",
        color: COLORS.green1,
        colorBg: COLORS.green1Trans,
        nav: "Plumbing",
    },
    {
        id: 7,
        icon: icons.Shifting,
        title: "Shifting",
        color: COLORS.cyan,
        colorBg: COLORS.cyanTrans,
        nav: "Shifting",
    },
    {
        id: 8,
        icon: icons.More,
        title: "More",
        color: COLORS.purple,
        colorBg: COLORS.purpleTrans,
        nav: "AllService",
    },
]

const AllService = [
    {
        id: 1,
        icon: icons.Cleaning,
        title: "Cleaning",
        color: COLORS.purple,
        colorBg: COLORS.purpleTrans,
        nav: "Cleaning",
    },
    {
        id: 2,
        icon: icons.Repairing,
        title: "Repairing",
        color: COLORS.orange,
        colorBg: COLORS.orangeTrans,
        nav: "Repairing",
    },
    {
        id: 3,
        icon: icons.Painting,
        title: "Painting",
        color: COLORS.blue,
        colorBg: COLORS.blueTrans,
        nav: "Painting",
    },
    {
        id: 4,
        icon: icons.Laundry,
        title: "Laundry",
        color: COLORS.lightYellow,
        colorBg: COLORS.lightYellowTrans,
        nav: "Laundry",
    },
    {
        id: 5,
        icon: icons.Appliance,
        title: "Appliance",
        color: COLORS.red,
        colorBg: COLORS.redTrans,
        nav: "Appliance",
    },
    {
        id: 6,
        icon: icons.Plumbing,
        title: "Plumbing",
        color: COLORS.green1,
        colorBg: COLORS.green1Trans,
        nav: "Plumbing",
    },
    {
        id: 7,
        icon: icons.Shifting,
        title: "Shifting",
        color: COLORS.cyan,
        colorBg: COLORS.cyanTrans,
        nav: "Shifting",
    },
    {
        id: 8,
        icon: icons.Massage,
        title: "Massage",
        color: null,
        colorBg: COLORS.roseTrans,
        nav: "Massage",
    },
    {
        id: 9,
        icon: icons.AC,
        title: "AC Repair",
        color: null,
        colorBg: COLORS.purpleTrans,
        nav: "AC Repair",
    },
    {
        id: 10,
        icon: icons.vehicle,
        title: "Vehicle",
        color: null,
        colorBg: COLORS.seaformTrans,
        nav: "Vehicle",
    },
    {
        id: 11,
        icon: icons.beauty,
        title: "Beauty",
        color: null,
        colorBg: COLORS.blueTrans,
        nav: "Beauty",
    },
    {
        id: 12,
        icon: icons.PC,
        title: "Electronics",
        color: null,
        colorBg: COLORS.orangeTrans,
        nav: "Electronics",
    },

    {
        id: 13,
        icon: icons.Salon,
        title: "Men's Salon",
        color: null,
        colorBg: COLORS.yellowTrans,
        nav: "Men's Salon",
    },
]

const popular = [
    {
        id: 1,
        title: "All",
    },
    {
        id: 2,
        title: "Cleaning",
    },
    {
        id: 3,
        title: "Repairing",
    },
    {
        id: 4,
        title: "Painting",
    },
    {
        id: 5,
        title: "Laundry",
    },
    {
        id: 6,
        title: "Appliance",
    },
    {
        id: 7,
        title: "Plumbing",
    },
    {
        id: 8,
        title: "Shifting",
    },
]

const Default = [
    {
        id: 1,
        cleaner: images.PaintS1,
        name: "Kylee Danford",
        title: "House Painting",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 2,
        cleaner: images.GadgetS3,
        name: "Alfanso Schuessler",
        title: "Repairing Services",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 3,
        cleaner: images.CleanerS3,
        name: "Sanjuanita Ordonez",
        title: "Washing Cleaning",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 4,
        cleaner: images.CleanerS4,
        name: "Freida Varnes",
        title: "Bathroom Cleaning",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    },
    {
        id: 5,
        cleaner: images.RepairS1,
        name: "Kylee Danford",
        title: "House Repairing",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 6,
        cleaner: images.RepairS2,
        name: "Alfanso Schuessler",
        title: "Floor Repairing",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 7,
        cleaner: images.RepairS3,
        name: "Sanjuanita Ordonez",
        title: "Washing Repairing",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 8,
        cleaner: images.RepairS4,
        name: "Freida Varnes",
        title: "Bathroom Repairing",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    },
    {
        id: 9,
        cleaner: images.PaintS1,
        name: "Kylee Danford",
        title: "House Painting",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 10,
        cleaner: images.PaintS2,
        name: "Alfanso Schuessler",
        title: "Floor Painting",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 11,
        cleaner: images.PaintS3,
        name: "Sanjuanita Ordonez",
        title: "Washing Painting",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 12,
        cleaner: images.PaintS4,
        name: "Freida Varnes",
        title: "Bathroom Painting",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    },
]

const Cleaning = [
    {
        id: 1,
        cleaner: images.CleanerS1,
        name: "Kylee Danford",
        title: "House Cleaning",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 2,
        cleaner: images.CleanerS2,
        name: "Alfanso Schuessler",
        title: "Floor Cleaning",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 3,
        cleaner: images.CleanerS3,
        name: "Sanjuanita Ordonez",
        title: "Washing Cleaning",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 4,
        cleaner: images.CleanerS4,
        name: "Freida Varnes",
        title: "Bathroom Cleaning",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    },
    {
        id: 5,
        cleaner: images.CleanerS5,
        name: "Kylee Danford",
        title: "Washing Cloths",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 6,
        cleaner: images.CleanerS6,
        name: "Alfanso Schuessler",
        title: "Kitchen Cleaning",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 7,
        cleaner: images.CleanerS7,
        name: "Sanjuanita Ordonez",
        title: "Window Cleaning",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 8,
        cleaner: images.CleanerS8,
        name: "Freida Varnes",
        title: "Bathroom Cleaning",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    }, {
        id: 9,
        cleaner: images.CleanerS9,
        name: "Kylee Danford",
        title: "Garden Cleaning",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 10,
        cleaner: images.CleanerS10,
        name: "Alfanso Schuessler",
        title: "Home Cleaning",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    }
]

const Repairing = [
    {
        id: 1,
        cleaner: images.RepairS1,
        name: "Kylee Danford",
        title: "House Repairing",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 2,
        cleaner: images.RepairS2,
        name: "Alfanso Schuessler",
        title: "Car Repairing",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 3,
        cleaner: images.RepairS3,
        name: "Sanjuanita Ordonez",
        title: "Motorcycle Repairing",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 4,
        cleaner: images.RepairS4,
        name: "Freida Varnes",
        title: "Walls Repairing",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    },
    {
        id: 5,
        cleaner: images.RepairS5,
        name: "Kylee Danford",
        title: "Machine Repairing",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 6,
        cleaner: images.RepairS6,
        name: "Alfanso Schuessler",
        title: "Bike Repairing",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 7,
        cleaner: images.RepairS7,
        name: "Sanjuanita Ordonez",
        title: "Gadget Repairing",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 8,
        cleaner: images.RepairS8,
        name: "Freida Varnes",
        title: "Bathroom Repairing",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    }, {
        id: 9,
        cleaner: images.RepairS9,
        name: "Kylee Danford",
        title: "House Repairing",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 10,
        cleaner: images.RepairS10,
        name: "Alfanso Schuessler",
        title: "Floor Repairing",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    }
]

const Painting = [
    {
        id: 1,
        cleaner: images.PaintS1,
        name: "Kylee Danford",
        title: "House Painting",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 2,
        cleaner: images.PaintS2,
        name: "Alfanso Schuessler",
        title: "Painting House",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 3,
        cleaner: images.PaintS3,
        name: "Sanjuanita Ordonez",
        title: "Painting Office Walls",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 4,
        cleaner: images.PaintS4,
        name: "Freida Varnes",
        title: "Painting House Walls",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    },
    {
        id: 5,
        cleaner: images.PaintS5,
        name: "Kylee Danford",
        title: "Painting Walls",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 6,
        cleaner: images.CleanerS6,
        name: "Alfanso Schuessler",
        title: "Ceiling Painting",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 7,
        cleaner: images.CleanerS7,
        name: "Sanjuanita Ordonez",
        title: "Ceiling Painting",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 8,
        cleaner: images.PaintS8,
        name: "Freida Varnes",
        title: "Bathroom Painting",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    }, {
        id: 9,
        cleaner: images.PaintS9,
        name: "Kylee Danford",
        title: "House Painting",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 10,
        cleaner: images.PaintS10,
        name: "Alfanso Schuessler",
        title: "Walls Painting",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    }
]

const Laundry = [
    {
        id: 1,
        cleaner: images.LaundryS1,
        name: "Kylee Danford",
        title: "Laundry Services",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 2,
        cleaner: images.LaundryS2,
        name: "Alfanso Schuessler",
        title: "Laundry Services",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 3,
        cleaner: images.LaundryS3,
        name: "Sanjuanita Ordonez",
        title: "Laundry Services",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 4,
        cleaner: images.LaundryS4,
        name: "Freida Varnes",
        title: "Laundry Services",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    },
    {
        id: 5,
        cleaner: images.LaundryS5,
        name: "Kylee Danford",
        title: "Laundry Services",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 6,
        cleaner: images.LaundryS6,
        name: "Alfanso Schuessler",
        title: "Laundry Services",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 7,
        cleaner: images.LaundryS7,
        name: "Sanjuanita Ordonez",
        title: "Laundry Services",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 8,
        cleaner: images.LaundryS8,
        name: "Freida Varnes",
        title: "Laundry Services",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    }, {
        id: 9,
        cleaner: images.LaundryS9,
        name: "Kylee Danford",
        title: "Laundry Services",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 10,
        cleaner: images.LaundryS10,
        name: "Alfanso Schuessler",
        title: "Laundry Services",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    }
]

const Appliance = [
    {
        id: 1,
        cleaner: images.GadgetS1,
        name: "Kylee Danford",
        title: "Household Appliance",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 2,
        cleaner: images.GadgetS2,
        name: "Alfanso Schuessler",
        title: "Appliance Services",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 3,
        cleaner: images.GadgetS3,
        name: "Sanjuanita Ordonez",
        title: "Kitchen Appliance",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 4,
        cleaner: images.GadgetS4,
        name: "Freida Varnes",
        title: "Appliance Services",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    },
    {
        id: 5,
        cleaner: images.GadgetS5,
        name: "Kylee Danford",
        title: "Kitchen Appliance",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 6,
        cleaner: images.GadgetS6,
        name: "Alfanso Schuessler",
        title: "Appliance Services",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 7,
        cleaner: images.GadgetS7,
        name: "Sanjuanita Ordonez",
        title: "Household Appliance",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 8,
        cleaner: images.GadgetS8,
        name: "Freida Varnes",
        title: "Appliance Services",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    }, {
        id: 9,
        cleaner: images.GadgetS9,
        name: "Kylee Danford",
        title: "Kitchen Appliance",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 10,
        cleaner: images.GadgetS10,
        name: "Alfanso Schuessler",
        title: "Appliance Services",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    }
]

const Plumbing = [
    {
        id: 1,
        cleaner: images.CleanerS1,
        name: "Kylee Danford",
        title: "Plumbing Repairing",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 2,
        cleaner: images.PlumberS2,
        name: "Alfanso Schuessler",
        title: "Plumbing Services",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 3,
        cleaner: images.PlumberS3,
        name: "Sanjuanita Ordonez",
        title: "Plumbing Repairing",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 4,
        cleaner: images.PlumberS4,
        name: "Freida Varnes",
        title: "Plumbing Repairing",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    },
    {
        id: 5,
        cleaner: images.PlumberS5,
        name: "Kylee Danford",
        title: "Plumbing Services",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 6,
        cleaner: images.PlumberS6,
        name: "Alfanso Schuessler",
        title: "Plumbing Repairing",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 7,
        cleaner: images.PlumberS7,
        name: "Sanjuanita Ordonez",
        title: "Plumbing Services",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 8,
        cleaner: images.PlumberS8,
        name: "Freida Varnes",
        title: "Plumbing Repairing",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    }, {
        id: 9,
        cleaner: images.PlumberS9,
        name: "Kylee Danford",
        title: "Plumbing Services",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 10,
        cleaner: images.PlumberS10,
        name: "Alfanso Schuessler",
        title: "Plumbing Services",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    }
]

const Shifting = [
    {
        id: 1,
        cleaner: images.ShiftingS1,
        name: "Kylee Danford",
        title: "House Shifting",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 2,
        cleaner: images.ShiftingS2,
        name: "Alfanso Schuessler",
        title: "Office Shifting",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 3,
        cleaner: images.ShiftingS3,
        name: "Sanjuanita Ordonez",
        title: "Villa Shifting",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 4,
        cleaner: images.ShiftingS4,
        name: "Freida Varnes",
        title: "House Shifting",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    },
    {
        id: 5,
        cleaner: images.ShiftingS5,
        name: "Kylee Danford",
        title: "Office Shifting",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 6,
        cleaner: images.ShiftingS6,
        name: "Alfanso Schuessler",
        title: "Villa Shifting",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 7,
        cleaner: images.ShiftingS7,
        name: "Sanjuanita Ordonez",
        title: "House Shifting",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 8,
        cleaner: images.ShiftingS8,
        name: "Freida Varnes",
        title: "Office Shifting",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    }, {
        id: 9,
        cleaner: images.ShiftingS9,
        name: "Kylee Danford",
        title: "Villa Shifting",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 10,
        cleaner: images.ShiftingS10,
        name: "Alfanso Schuessler",
        title: "House Shifting",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    }
]

const Notification = [
    {
        id: 1,
        date: "Today",

    },
    {
        id: 2,
        date: "Yesterday",

    },
    {
        id: 3,
        date: "April 11, 2023",

    },
]

const TodayNoti = [
    {
        id: 1,
        imageBg: icons.Bubble,
        circle: icons.PurpleCircle,
        color: COLORS.purple,
        icon: icons.wallet,
        title: "Payment Successful!",
        subTitle: "You have made a services payment",
    },
    {
        id: 2,
        imageBg: icons.Bubble,
        circle: icons.PurpleCircle,
        color: COLORS.rose,
        icon: icons.category,
        title: "New Category Service!",
        subTitle: "Now the plumbing service is available",
    },
]

const YesterdayNoti = [
    {
        id: 1,
        imageBg: icons.Bubble,
        circle: icons.PurpleCircle,
        color: COLORS.YellowBG,
        icon: icons.wallet,
        title: "Today's Special Offers!",
        subTitle: "You get a special promo today!",
    },
]

const AprilNoti = [
    {
        id: 1,
        imageBg: icons.Bubble,
        circle: icons.PurpleCircle,
        color: COLORS.purple,
        icon: icons.wallet,
        title: "Today's Special Offers!",
        subTitle: "You get a special promo today!",
    },
    {
        id: 2,
        imageBg: icons.Bubble,
        circle: icons.PurpleCircle,
        color: COLORS.seaform,
        icon: icons.Profile,
        title: "Credit Card Connected!",
        subTitle: "Credit Card has been linked!",
    },
]

const Bookmark = [
    {
        id: 1,
        cleaner: images.CleanerS1,
        name: "Kylee Danford",
        title: "House Cleaning",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 2,
        cleaner: images.CleanerS2,
        name: "Alfanso Schuessler",
        title: "Floor Cleaning",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 3,
        cleaner: images.CleanerS3,
        name: "Sanjuanita Ordonez",
        title: "Washing Cleaning",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 4,
        cleaner: images.CleanerS4,
        name: "Freida Varnes",
        title: "Bathroom Cleaning",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    },
    {
        id: 5,
        cleaner: images.RepairS1,
        name: "Kylee Danford",
        title: "House Repairing",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 6,
        cleaner: images.RepairS2,
        name: "Alfanso Schuessler",
        title: "Floor Repairing",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 7,
        cleaner: images.RepairS3,
        name: "Sanjuanita Ordonez",
        title: "Washing Repairing",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 8,
        cleaner: images.RepairS4,
        name: "Freida Varnes",
        title: "Bathroom Repairing",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    },
    {
        id: 9,
        cleaner: images.PaintS1,
        name: "Kylee Danford",
        title: "House Painting",
        price: "$25",
        star: icons.Rating,
        rating: 4.8,
        review: "8,289",
        bg: COLORS.cyanBG,
    },
    {
        id: 10,
        cleaner: images.PaintS2,
        name: "Alfanso Schuessler",
        title: "Floor Painting",
        price: "$20",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.PinkBG,
    },
    {
        id: 11,
        cleaner: images.PaintS3,
        name: "Sanjuanita Ordonez",
        title: "Washing Painting",
        price: "$24",
        star: icons.Rating,
        rating: 4.7,
        review: "7,938",
        bg: COLORS.YellowBG,
    },
    {
        id: 12,
        cleaner: images.PaintS4,
        name: "Freida Varnes",
        title: "Bathroom Painting",
        price: "$24",
        star: icons.Rating,
        rating: 4.9,
        review: "6,182",
        bg: COLORS.OrangeBG,
    },
]

const SearchHistory = [
    {
        id: 1,
        title: "Motorcycle Repairing"
    },
    {
        id: 2,
        title: "Painting the walls"
    },
    {
        id: 3,
        title: "Water Foucet Reapiring"
    },
    {
        id: 4,
        title: "Window Cleaning"
    },
    {
        id: 5,
        title: "House Shifting"
    }, {
        id: 6,
        title: "Computer Repairing"
    }, {
        id: 7,
        title: "Cloth Laundry"
    }, {
        id: 8,
        title: "Floor Wash"
    },
]

const Rating = [
    {
        id: 1,
        star: "All",
    },
    {
        id: 2,
        star: "5",
    },
    {
        id: 3,
        star: "4",
    },
    {
        id: 4,
        star: "3",
    },
    {
        id: 5,
        star: "2",
    },
    {
        id: 6,
        star: "1",
    },
]

const gallary = [
    {
        id: 1,
        image: images.IMG1,
    },
    {
        id: 2,
        image: images.IMG2,
    },
    {
        id: 3,
        image: images.IMG3,
    },
    {
        id: 4,
        image: images.IMG4,
    },
    {
        id: 5,
        image: images.IMG5,
    },
    {
        id: 6,
        image: images.IMG6,
    },
    {
        id: 7,
        image: images.IMG7,
    },
    {
        id: 8,
        image: images.IMG8,
    },
]

const review = [
    {
        id: 1,
        name: 'Lauralee Quintero',
        likes: '724',
        time: '3 week ago',
        rating: '5',
        profile: icons.Profile3D,
        review: 'With Best Service I had a very good experience',
    },
    {
        id: 2,
        name: 'Clinton Mcclure',
        likes: '783',
        time: '1 week ago',
        rating: '4',
        profile: icons.Profile3DGirl,
        review: 'Awesome this is what i was looking for, i recommend to everyone❤💖',
    },
    {
        id: 3,
        name: 'Chieko Chute',
        likes: '597',
        time: '2 week ago',
        rating: '5',
        profile: icons.Profile3D,
        review: 'Workers are professional and the results are very satisfying! I like it very much!❤💯',
    },
    {
        id: 4,
        name: 'Clinton Mcclure',
        likes: '11',
        time: '5 week ago',
        rating: '2',
        profile: icons.Profile3DGirl,
        review: 'Avarage Work',
    },
    {
        id: 5,
        name: 'Chieko Chute',
        likes: '97',
        time: '2 week ago',
        rating: '3',
        profile: icons.Profile3D,
        review: 'Workers are professional and the results are very satisfying! I like it very much!❤💯',
    },
    {
        id: 6,
        name: 'Clinton Mcclure',
        likes: '335',
        time: '1 week ago',
        rating: '1',
        profile: icons.Profile3DGirl,
        review: 'Avarage Work',
    },
]

const cleaningBookings = [
    {
        id: 1,
        bookings: 0,
        serviceName: 'Living Room',
        price: '20',
    },
    {
        id: 2,
        bookings: 1,
        serviceName: 'Terrace',
        price: '25',
    },
    {
        id: 3,
        bookings: 2,
        serviceName: 'Bedroom',
        price: '15',
    },
    {
        id: 4,
        bookings: 5,
        serviceName: 'Bathroom',
        price: '30',
    },
    {
        id: 5,
        bookings: 1,
        serviceName: 'Kitchen',
        price: '20',
    },
    {
        id: 6,
        bookings: 1,
        serviceName: 'Dining Room',
        price: '10',
    },
    {
        id: 7,
        bookings: 2,
        serviceName: 'Garbage',
        price: '10',
    },
]

const Calls = [
    {
        id: 1,
        name: 'Lauralee Quintero',
        category: 'Incoming',
        date: 'Dec 19, 2024',
        image: images.CleanerS4,
    },
    {
        id: 2,
        name: 'Tanner Stafford',
        category: 'Outgoing',
        date: 'Dec 17, 2024',
        image: images.PlumberS1,
    },
    {
        id: 3,
        name: 'Augustina Midgett',
        category: 'Missed',
        date: 'Dec 19, 2024',
        image: images.PaintS4,
    },
    {
        id: 4,
        name: 'Lauralee Quintero',
        category: 'Incoming',
        date: 'Dec 19, 2024',
        image: images.LaundryS5,
    },
    {
        id: 5,
        name: 'Tanner Stafford',
        category: 'Outgoing',
        date: 'Dec 17, 2024',
        image: images.RepairS6,
    },
    {
        id: 6,
        name: 'Augustina Midgett',
        category: 'Missed',
        date: 'Nov 28, 2024',
        image: images.CleanerS8,
    },
    {
        id: 7,
        name: 'Lauralee Quintero',
        category: 'Incoming',
        date: 'Nov 24, 2024',
        image: images.CleanerS5,
    },
    {
        id: 8,
        name: 'Tanner Stafford',
        category: 'Outgoing',
        date: 'Nov 14, 2024',
        image: images.ShiftingS2,
    },
    {
        id: 9,
        name: 'Augustina Midgett',
        category: 'Missed',
        date: 'Oct 30, 2024',
        image: images.CleanerS10,
    },
]

const Chats = [
    {
        id: 1,
        name: 'Jenny Wilson',
        description: 'I have Booked your house..',
        image: images.CleanerS2,
        newMSG: 2,
        time: '13.29',
    },
    {
        id: 2,
        name: 'Alfonzo Schuessler',
        description: 'I just finished it',
        image: images.CleanerS7,
        newMSG: 3,
        time: '10:48',
    },
    {
        id: 3,
        name: 'Benny Spanbuer',
        description: 'OMG, this is amazing..🔥',
        image: images.LaundryS6,
        newMSG: 0,
        time: '09:25',
    },
    {
        id: 4,
        name: 'Marci Senter',
        description: 'Wow, this is really epic 😊',
        image: images.RepairS3,
        newMSG: 2,
        time: 'Yesterday',
    },
    {
        id: 5,
        name: 'Kylee Danford',
        description: 'just ideas for next time',
        image: images.CleanerS7,
        newMSG: 0,
        time: 'Dec 20, 2024',
    },
    {
        id: 6,
        name: 'Merrill Kervin',
        description: 'How are you? 😊😁',
        image: images.PaintS5,
        newMSG: 0,
        time: 'Dec 20, 2024',
    },
    {
        id: 7,
        name: 'Pedro Huard',
        description: 'perfect..💯🔥',
        image: images.CleanerS7,
        newMSG: 0,
        time: 'Dec 18, 2024',
    },
    {
        id: 8,
        name: 'Edgar Torrey',
        description: 'just ideas for next time',
        image: images.PaintS8,
        newMSG: 0,
        time: 'Dec 11, 2024',
    },
]

const PaymentCard = [
    {
        id: 1,
        card: 'Razorpay',
        cardNo: '',
        image: icons.Razorpay,
        status: 'connected',
    },
    {
        id: 2,
        card: 'Cash on Delivery',
        cardNo: '',
        image: icons.cash,
        status: 'connected',
    },
    {
        id: 3,
        card: 'Wallet',
        cardNo: '',
        image: icons.walletBrown,
        status: 'connected',
    },
]

const language = [
    {
        id: 1,
        suggested: true,
        name: 'English (US)',
    },
    {
        id: 2,
        suggested: true,
        name: 'English (UK)',
    },
    {
        id: 3,
        suggested: false,
        name: 'Mandarin',
    },
    {
        id: 4,
        suggested: false,
        name: 'Hindi',
    },
    {
        id: 5,
        suggested: false,
        name: 'Spanish',
    },
    {
        id: 6,
        suggested: false,
        name: 'French',
    },
    {
        id: 7,
        suggested: false,
        name: 'Arabic',
    },
    {
        id: 8,
        suggested: false,
        name: 'Bengali',
    },
    {
        id: 9,
        suggested: false,
        name: 'Russian',
    },
    {
        id: 10,
        suggested: false,
        name: 'Indonesia',
    },
    {
        id: 11,
        suggested: false,
        name: 'Japanese',
    },
    {
        id: 12,
        suggested: false,
        name: 'Korean',
    },
]

const Privacy = [
    {
        id: 1,
        name: 'Types of Data We Collect',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae ultricies leo integer malesuada nunc. Augue mauris augue neque gravida in fermentum. Vitae auctor eu augue ut lectus arcu bibendum. Nisl nisi scelerisque eu ultrices. Augue lacus viverra vitae congue. Turpis egestas sed tempus urna et pharetra pharetra. Habitasse platea dictumst vestibulum rhoncus est.",
    },
    {
        id: 2,
        name: 'Use of Your Personal Data',
        description: "Ornare quam viverra orci sagittis eu volutpat odio. Neque convallis a cras semper auctor neque vitae. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Viverra nibh cras pulvinar mattis nunc sed blandit libero. Ultrices tincidunt arcu non sodales neque. Phasellus egestas tellus rutrum tellus. Elit at imperdiet dui accumsan sit amet nulla facilisi.",
    },
    {
        id: 3,
        name: 'Disclosure of Your Personal Data',
        description: "Dui sapien eget mi proin. Libero enim sed faucibus turpis in. Mauris a diam maecenas sed enim ut sem. Iaculis nunc sed augue lacus viverra vitae congue eu consequat. Eget magna fermentum iaculis eu non diam phasellus. Enim sed faucibus turpis in eu. At augue eget arcu dictum. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Urna porttitor rhoncus dolor purus non enim praesent. Ornare arcu odio ut sem nulla pharetra. ",
    },
    {
        id: 4,
        name: 'Privacy Laws',
        description: "Habitant morbi tristique senectus et netus et malesuada fames. Egestas sed sed risus pretium quam. Nunc non blandit massa enim nec. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Sed augue lacus viverra vitae congue eu. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. Sit amet venenatis urna cursus eget nunc scelerisque. Lacus luctus accumsan tortor posuere. Semper feugiat nibh sed pulvinar. ",
    },
    {
        id: 5,
        name: 'Use of Your Personal Data',
        description: "Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Non blandit massa enim nec. Pulvinar sapien et ligula ullamcorper. Senectus et netus et malesuada fames ac turpis egestas. Eu scelerisque felis imperdiet proin fermentum leo vel orci porta. Nisl suscipit adipiscing bibendum est. Sit amet cursus sit amet dictum. Commodo nulla facilisi nullam vehicula ipsum a. Urna id volutpat lacus laoreet non. Malesuada fames ac turpis egestas. ",
    },
    {
        id: 6,
        name: 'Types of Data We Collect',
        description: "Purus in mollis nunc sed id semper risus in hendrerit. Lorem dolor sed viverra ipsum nunc aliquet. Ut ornare lectus sit amet est. Ultrices gravida dictum fusce ut placerat orci nulla. Mauris rhoncus aenean vel elit scelerisque mauris. Arcu dui vivamus arcu felis bibendum ut. Integer vitae justo eget magna fermentum iaculis. Purus non enim praesent elementum facilisis leo vel fringilla est. Sapien eget mi proin sed libero.",
    },
]

const FriendInfo = [
    {
        id: 1,
        invited: false,
        name: 'Tynisha Obey',
        profile: images.Friend1,
        contactNo: '+91 1234567890',
    },
    {
        id: 2,
        invited: false,
        profile: images.Friend2,
        name: 'Florencia Dorrance',
        contactNo: '+91 5432167890',
    },
    {
        id: 3,
        invited: false,
        profile: images.Friend3,
        name: 'Chantal Shelburne',
        contactNo: '+91 9685736251',
        
    },
    {
        id: 4,
        invited: false,
        profile: images.Friend4,
        name: 'Maryaland Winkles',
        contactNo: '+91 8192037465',
    },
    {
        id: 5,
        invited: false,
        profile: images.Friend5,
        name: 'Rodolfo Goode',
        contactNo: '+91 6688367890',
    },
    {
        id: 6,
        invited: false,
        profile: images.Friend6,
        name: 'Benny Spanbauer',
        contactNo: '+91 5434345890',
    },
    {
        id: 7,
        invited: false,
        profile: images.Friend7,
        name: 'Tynisha Obey',
        contactNo: '+91 1234567890',
    },
    {
        id: 8,
        invited: false,
        profile: images.Friend8,
        name: 'Florencia Dorrance',
        contactNo: '+91 5432167890',
    },
    {
        id: 9,
        invited: false,
        profile: images.Friend9,
        name: 'Chantal Shelburne',
        contactNo: '+91 9685736251',
    },
    {
        id: 10,
        invited: false,
        profile: images.Friend10,
        name: 'Maryaland Winkles',
        contactNo: '+91 8192037465',
    },
    {
        id: 11,
        invited: false,
        profile: images.Friend11,
        name: 'Rodolfo Goode',
        contactNo: '+91 6688367890',
    },
    {
        id: 12,
        invited: false,
        profile: images.Friend12,
        name: 'Benny Spanbauer',
        contactNo: '+91 5434345890',
    },
    {
        id: 13,
        invited: false,
        profile: images.Friend13,
        name: 'Chantal Shelburne',
        contactNo: '+91 9685736251',
    },
    {
        id: 14,
        invited: false,
        profile: images.Friend14,
        name: 'Maryaland Winkles',
        contactNo: '+91 8192037465',
    },
    {
        id: 15,
        invited: false,
        profile: images.Friend15,
        name: 'Rodolfo Goode',
        contactNo: '+91 6688367890',
    },
]

const SettingCategory = [
    {
        id: 1,
        setting: 'General',
    },
    {
        id: 2,
        setting: 'Account',
    },
    {
        id: 3,
        setting: 'Service',
    },
    {
        id: 4,
        setting: 'Payment',
    },
    {
        id: 5,
        setting: 'Notification',
    },
    {
        id: 6,
        setting: 'Offer',
    },
    {
        id: 7,
        setting: 'Review',
    },
    {
        id: 8,
        setting: 'Bookings',
    },
]

const helpData = [
    {
        id: 1,
        title: 'What is ABCD?',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Posuere ac ut consequat semper viverra nam.'
    },
    {
        id: 2,
        title: 'How to use ABCD?',
        description: 'Sed egestas egestas fringilla phasellus faucibus. Diam in arcu cursus euismod quis viverra nibh. Tincidunt arcu non sodales neque sodales ut etiam. Malesuada fames ac turpis egestas.'
    },
    {
        id: 3,
        title: 'How do I cancel a booking?',
        description: 'Feugiat in ante metus dictum at tempor commodo. Vitae et leo duis ut diam quam nulla porttitor. Habitant morbi tristique senectus et netus et malesuada.'
    },
    {
        id: 4,
        title: 'Is ABCD free to use?',
        description: 'Feugiat in ante metus dictum at tempor commodo. Vitae et leo duis ut diam quam nulla porttitor. Habitant morbi tristique senectus et netus et malesuada.'

    },
    {
        id: 5,
        title: 'How to make offer on ABCD?',
        description: 'Feugiat in ante metus dictum at tempor commodo. Vitae et leo duis ut diam quam nulla porttitor. Habitant morbi tristique senectus et netus et malesuada.'
    },
]

const Bookings = [
    // Upcoming
    {
        id: 1,
        service: "House Cleaning",
        Name: "Jenny Wilson",
        status: "Upcoming",
        image: images.CleanerS9,
        date: 'Dec 12, 2024',
        time: '13:00 - 15:00 PM',
        Location: '1691 Faridabad',
        profile: icons.Profile3D,
    },
    {
        id: 2,
        service: "Application Service",
        Name: "Alex Nguyen",
        status: "Upcoming",
        image: images.GadgetS2,
        date: 'Dec 12, 2024',
        time: '13:00 - 15:00 PM',
        Location: '1691 Faridabad',
        profile: icons.Profile3D,
    },
    {
        id: 3,
        service: "Laundry Service",
        Name: "Jenny Wilson",
        status: "Upcoming",
        image: images.LaundryS1,
        date: 'Dec 12, 2024',
        time: '13:00 - 15:00 PM',
        Location: '1691 Faridabad',
        profile: icons.Profile3D,
    },
    {
        id: 4,
        service: "Painting Service",
        Name: "Alex Nguyen",
        status: "Upcoming",
        image: images.PaintS1,
        date: 'Dec 12, 2024',
        time: '13:00 - 15:00 PM',
        Location: '1691 Faridabad',
        profile: icons.Profile3D,
    },

    // Completed
    {
        id: 5,
        service: "Electronic Service",
        Name: "Jenny Wilson",
        status: "Completed",
        image: images.GadgetS2,
        date: 'Dec 12, 2024',
        time: '13:00 - 15:00 PM',
        Location: '1691 Faridabad',
        profile: icons.Profile3D,
    },
    {
        id: 6,
        service: "Repair Service",
        Name: "Alex Nguyen",
        status: "Completed",
        image: images.RepairS6,
        date: 'Dec 12, 2024',
        time: '13:00 - 15:00 PM',
        Location: '1691 Faridabad',
        profile: icons.Profile3D,
    },
    {
        id: 7,
        service: "Laundry Service",
        Name: "Jenny Wilson",
        status: "Completed",
        image: images.LaundryS6,
        date: 'Dec 12, 2024',
        time: '13:00 - 15:00 PM',
        Location: '1691 Faridabad',
        profile: icons.Profile3D,
    },
    {
        id: 8,
        service: "Painting Service",
        Name: "Alex Nguyen",
        status: "Completed",
        image: images.PaintS8,
        date: 'Dec 12, 2024',
        time: '13:00 - 15:00 PM',
        Location: '1691 Faridabad',
        profile: icons.Profile3D,
    },

    // Cancelled
    {
        id: 9,
        service: "Gadget Service",
        Name: "Jenny Wilson",
        status: "Cancelled",
        image: images.GadgetS2,
        date: 'Dec 12, 2024',
        time: '13:00 - 15:00 PM',
        Location: '1691 Faridabad',
        profile: icons.Profile3D,
    },
    {
        id: 10,
        service: "Kitchen Cleaning",
        Name: "Alex Nguyen",
        status: "Cancelled",
        image: images.CleanerS9,
        date: 'Dec 12, 2024',
        time: '13:00 - 15:00 PM',
        Location: '1691 Faridabad',
        profile: icons.Profile3D,
    },
    {
        id: 11,
        service: "Repair Service",
        Name: "Jenny Wilson",
        status: "Cancelled",
        image: images.RepairS4,
        date: 'Dec 12, 2024',
        time: '13:00 - 15:00 PM',
        Location: '1691 Faridabad',
        profile: icons.Profile3D,
    },
    {
        id: 12,
        service: "Home Service",
        Name: "Alex Nguyen",
        status: "Cancelled",
        image: images.Cleaner4,
        date: 'Dec 12, 2024',
        time: '13:00 - 15:00 PM',
        Location: '1691 Faridabad',
        profile: icons.Profile3D,
    },
]

const Offer = [
    {
        id: 1,
        code: 'SUPER25',
        imageBg: icons.Bubble,
        star: icons.PurpleStar,
        circle: icons.PurpleCircle,
        color: COLORS.purple,
        icon: icons.Voucher,
        title: "Special 25% Off",
        subTitle: "Special promo only for today!",
    },
    {
        id: 2,
        code: 'SUPER30',
        imageBg: icons.Bubble,
        star: icons.PurpleStar,
        circle: icons.PurpleCircle,
        color: COLORS.yellow,
        icon: icons.Voucher,
        title: "Discount 30% Off",
        subTitle: "New User Special Promo",
    },
    {
        id: 3,
        code: 'TODAY20',
        imageBg: icons.Bubble,
        star: icons.PurpleStar,
        circle: icons.PurpleCircle,
        color: COLORS.rose,
        icon: icons.Voucher,
        title: "Special 20% Off",
        subTitle: "Special promo only for today!",
    },
    {
        id: 4,
        code: 'TODAY40',
        imageBg: icons.Bubble,
        star: icons.PurpleStar,
        circle: icons.PurpleCircle,
        color: COLORS.seaform,
        icon: icons.Voucher,
        title: "Discount 40% Off",
        subTitle: "Special Promo valid for today!",
    },
    {
        id: 5,
        code: 'TODAY35',
        imageBg: icons.Bubble,
        star: icons.PurpleStar,
        circle: icons.PurpleCircle,
        color: COLORS.orange,
        icon: icons.Voucher,
        title: "Discount 35% Off",
        subTitle: "Special Promo only for today!",
    },
    {
        id: 6,
        code: 'SPECIAL25',
        imageBg: icons.Bubble,
        star: icons.PurpleStar,
        circle: icons.PurpleCircle,
        color: COLORS.purple,
        icon: icons.Voucher,
        title: "Special 25% Off",
        subTitle: "Special promo only for today!",
    },
    {
        id: 7,
        code: 'SPECIAL30',
        imageBg: icons.Bubble,
        star: icons.PurpleStar,
        circle: icons.PurpleCircle,
        color: COLORS.yellow,
        icon: icons.Voucher,
        title: "Discount 30% Off",
        subTitle: "New User Special Promo",
    },
    {
        id: 8,
        code: 'TODAY20',
        imageBg: icons.Bubble,
        star: icons.PurpleStar,
        circle: icons.PurpleCircle,
        color: COLORS.rose,
        icon: icons.Voucher,
        title: "Special 20% Off",
        subTitle: "Special promo only for today!",
    },
    {
        id: 9,
        code: 'DISCOUNT40',
        imageBg: icons.Bubble,
        star: icons.PurpleStar,
        circle: icons.PurpleCircle,
        color: COLORS.seaform,
        icon: icons.Voucher,
        title: "Discount 40% Off",
        subTitle: "Special Promo valid for today!",
    },
    {
        id: 10,
        code: 'DISCOUNT35',
        imageBg: icons.Bubble,
        star: icons.PurpleStar,
        circle: icons.PurpleCircle,
        color: COLORS.orange,
        icon: icons.Voucher,
        title: "Discount 35% Off",
        subTitle: "Special Promo only for today!",
    },
]

const Time = [
    {
        id: 1,
        title: '09:00 AM',
    },
    {
        id: 2,
        title: '10:00 AM',
    },
    {
        id: 3,
        title: '11:00 AM',
    },
    {
        id: 4,
        title: '12:00 AM',
    },
    {
        id: 5,
        title: '13:00 PM',
    },
    {
        id: 6,
        title: '14:00 PM',
    },
    {
        id: 7,
        title: '15:00 PM',
    },
    {
        id: 8,
        title: '16:00 PM',
    },
]

export default {

    // SPLASH SCREEN
    slides,

    // OFFERS
    banners,
    service,

    // ALL SERVICE
    AllService,

    // POPULAR SECTION
    popular, Default, Cleaning,
    Repairing, Painting, Laundry,
    Appliance, Plumbing, Shifting,

    // Notification
    Notification, TodayNoti,
    YesterdayNoti, AprilNoti,

    // bookmark
    Bookmark,

    SearchHistory,
    Rating,

    // gallery
    gallary,
    // review
    review,

    // bookings
    cleaningBookings,

    // chats
    Chats, Calls,

    // profile section
    // payment
    PaymentCard,
    // lanuage
    language,
    // privacy
    Privacy,
    // friend info
    FriendInfo,
    // setting Category
    SettingCategory,
    // help info
    helpData,

    // Booking
    Bookings,
    // Timing
    Time,
    
    // promo Offer
    Offer,
}